// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrcraqilcvkbwxqfguss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyY3JhcWlsY3ZrYnd4cWZndXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTgwNjUsImV4cCI6MjA1OTIzNDA2NX0.TWz-ByQOfDEmuP7Rg9Wu_02qDWPv14vmayJq7jEyKE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);